import { Metadata } from "next"


export const metadata: Metadata = {
    title: 'Terms and Conditions',
    description: 'Generated by Next.js',
}


export default function ProductLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}